name: Goldenold
title: " Goldenold | All you need to know about old"
description: bolg about ...
tags:
  - relationship
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@xyz.com
disqus_username: disqus_username
